/* tree.c */
xmlNodePtr xmlRemoveNs(xmlNodePtr tree, xmlNsPtr ns);
xmlNsPtr xmlReplaceNs(xmlNodePtr tree, xmlNsPtr oldNs, xmlNsPtr newNs);
/* xmlreader.c */
int xmlStreamReaderRead(xmlTextReaderPtr reader);
int xmlStreamReaderReadState(xmlTextReaderPtr reader);
xmlNodePtr xmlStreamReaderExpand(xmlTextReaderPtr reader);
int xmlStreamReaderNext(xmlTextReaderPtr reader);
xmlChar *xmlStreamReaderReadInnerXml(xmlTextReaderPtr reader);
xmlChar *xmlStreamReaderReadOuterXml(xmlTextReaderPtr reader);
xmlChar *xmlStreamReaderReadString(xmlTextReaderPtr reader);
int xmlStreamReaderReadBase64(xmlTextReaderPtr reader, unsigned char *array, int offset, int len);
int xmlStreamReaderReadBinHex(xmlTextReaderPtr reader, unsigned char *array, int offset, int len);
xmlTextReaderPtr xmlNewStreamReader(xmlParserInputBufferPtr input, const char *URI);
xmlTextReaderPtr xmlNewStreamReaderFilename(const char *URI);
void xmlFreeStreamReader(xmlTextReaderPtr reader);
int xmlStreamReaderClose(xmlTextReaderPtr reader);
xmlChar *xmlStreamReaderGetAttributeNo(xmlTextReaderPtr reader, int no);
xmlChar *xmlStreamReaderGetAttribute(xmlTextReaderPtr reader, const xmlChar *name);
xmlChar *xmlStreamReaderGetAttributeNs(xmlTextReaderPtr reader, const xmlChar *localName, const xmlChar *namespaceURI);
xmlParserInputBufferPtr xmlStreamReaderGetRemainder(xmlTextReaderPtr reader);
xmlChar *xmlStreamReaderLookupNamespace(xmlTextReaderPtr reader, const xmlChar *prefix);
int xmlStreamReaderMoveToAttributeNo(xmlTextReaderPtr reader, int no);
int xmlStreamReaderMoveToAttribute(xmlTextReaderPtr reader, const xmlChar *name);
int xmlStreamReaderMoveToAttributeNs(xmlTextReaderPtr reader, const xmlChar *localName, const xmlChar *namespaceURI);
int xmlStreamReaderMoveToFirstAttribute(xmlTextReaderPtr reader);
int xmlStreamReaderMoveToNextAttribute(xmlTextReaderPtr reader);
int xmlStreamReaderMoveToElement(xmlTextReaderPtr reader);
int xmlStreamReaderReadAttributeValue(xmlTextReaderPtr reader);
int xmlStreamReaderAttributeCount(xmlTextReaderPtr reader);
int xmlStreamReaderNodeType(xmlTextReaderPtr reader);
int xmlStreamReaderIsEmptyElement(xmlTextReaderPtr reader);
xmlChar *xmlStreamReaderLocalName(xmlTextReaderPtr reader);
xmlChar *xmlStreamReaderName(xmlTextReaderPtr reader);
xmlChar *xmlStreamReaderPrefix(xmlTextReaderPtr reader);
xmlChar *xmlStreamReaderNamespaceUri(xmlTextReaderPtr reader);
xmlChar *xmlStreamReaderBaseUri(xmlTextReaderPtr reader);
int xmlStreamReaderDepth(xmlTextReaderPtr reader);
int xmlStreamReaderHasAttributes(xmlTextReaderPtr reader);
int xmlStreamReaderHasValue(xmlTextReaderPtr reader);
xmlChar *xmlStreamReaderValue(xmlTextReaderPtr reader);
int xmlStreamReaderIsDefault(xmlTextReaderPtr reader);
int xmlStreamReaderQuoteChar(xmlTextReaderPtr reader);
xmlChar *xmlStreamReaderXmlLang(xmlTextReaderPtr reader);
int xmlStreamReaderNormalization(xmlTextReaderPtr reader);
int xmlStreamReaderSetParserProp(xmlTextReaderPtr reader, int prop, int value);
int xmlStreamReaderGetParserProp(xmlTextReaderPtr reader, int prop);
xmlNodePtr xmlStreamReaderCurrentNode(xmlTextReaderPtr reader);
xmlDocPtr xmlStreamReaderCurrentDoc(xmlTextReaderPtr reader);
int xmlStreamReaderRelaxNGSetSchema(xmlTextReaderPtr reader, xmlRelaxNGPtr schema);
int xmlStreamReaderRelaxNGValidate(xmlTextReaderPtr reader, const char *rng);
int xmlStreamReaderLocatorLineNumber(xmlTextReaderLocatorPtr locator);
xmlChar *xmlStreamReaderLocatorBaseURI(xmlTextReaderLocatorPtr locator);
void xmlStreamReaderSetErrorHandler(xmlTextReaderPtr reader, xmlTextReaderErrorFunc f, void *arg);
int xmlStreamReaderIsValid(xmlTextReaderPtr reader);
void xmlStreamReaderGetErrorHandler(xmlTextReaderPtr reader, xmlTextReaderErrorFunc *f, void **arg);
